### ISSUE TITLE
f:display throws NullPointerException when a referenced field is null

### ISSUE THREAD

**Issue by igoraguiar** [grails3-plugins/fields#10]
At FormFieldsTagLib.groovy:576 (https://github.com/grails3-plugins/fields/blob/master/grails-app/taglib/grails/plugin/formfields/FormFieldsTagLib.groovy#L576)  f:display tries to access the id field of the referenced fields:
```groovy
    private CharSequence displayAssociation(value, GrailsDomainClass referencedDomainClass) {
        g.link(controller: referencedDomainClass.propertyName, action: "show", id: value.id, value.toString().encodeAsHTML())
    }
```
If the referenced field is null, a NPE is thrown. 
Relevant stacktrace:
```
rg.grails.taglib.GrailsTagException: [views/simcard/show.gsp:22] Error executing tag <f:display>: Cannot get property 'id' on null object
	at org.grails.gsp.GroovyPage.throwRootCause(GroovyPage.java:445) ~[grails-gsp-3.0.2.jar:3.0.2]
	at org.grails.gsp.GroovyPage.invokeTag(GroovyPage.java:388) ~[grails-gsp-3.0.2.jar:3.0.2]
	at sun.reflect.GeneratedMethodAccessor236.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) ~[groovy-2.4.3.jar:2.4.3]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:382) ~[groovy-2.4.3.jar:2.4.3]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:151) ~[groovy-2.4.3.jar:2.4.3]
	at home_igor_geocontrol_repositorio_cgs_cgs_web_grails_app_views_simcard_show_gsp$_run_closure2.doCall(home_igor_geocontrol_repositorio_cgs_cgs_web_grails_app_views_simcard_show_gsp:58) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
Caused by: java.lang.NullPointerException: Cannot get property 'id' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:169) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:293) ~[groovy-2.4.3.jar:2.4.3]
	at grails.plugin.formfields.FormFieldsTagLib.displayAssociation(FormFieldsTagLib.groovy:576) ~[fields-2.0.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) ~[springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61) ~[groovy-2.4.3.jar:2.4.3]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171) ~[groovy-2.4.3.jar:2.4.3]
	at grails.plugin.formfields.FormFieldsTagLib.renderDefaultDisplay(FormFieldsTagLib.groovy:532) ~[fields-2.0.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
```

**Comment by igoraguiar** [comment]
* Grails version: 3.0.2
* Fields plugin version: 2.0.2

**Comment by pledbrook** [comment]
I think a guard on the `link` tag should be sufficient. In other words, wrap `g.link()` with `if (value) { ... }`. Are there tests that can be updated?
