### ISSUE TITLE
[views/stock/create.gsp:35] [views/stock/create.gsp:30] Tag [all] currently only supports domain types

### ISSUE THREAD

**Issue by xuchaoo** [grails3-plugins/fields#2]
```xml
<g:form action="save">
                <fieldset class="form">
                    <f:all bean="stock"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
```
![image](https://cloud.githubusercontent.com/assets/976008/7669295/c494c9a6-fc9e-11e4-8685-ad1494a2bbfb.png)

**Comment by xuchaoo** [comment]
![image](https://cloud.githubusercontent.com/assets/976008/7669304/156318b0-fc9f-11e4-8419-d31eadf4abd9.png)

**Comment by xuchaoo** [comment]
grails has so many bugs that I have to give up .  It's heavy and not simple. gradle is also confused me.
People will not use grails to create a website which have big press. people just want to find a more quick method to implements CURD. I use java to build my backend and grails fontend. No one like a heavy and complex fontend framework through It's really convenent(with so many 坑).

**Comment by xuchaoo** [comment]
It's not a bug!!, but the document is really misleading...好坑！

**Comment by xuchaoo** [comment]
Any body?

**Comment by jeffbrown** [comment]
> Any body?

What do you mean by that?  

Above you said "It's not a bug".  Why do you say that?

**Comment by jeffbrown** [comment]
See https://github.com/grails3-plugins/fields/blob/4248a0f2eddc4ebb768e3e266c3bf2a34bd451a5/grails-app/taglib/grails/plugin/formfields/FormFieldsTagLib.groovy#L82.  I think the docs should be explicit about that.  I can't tell if that is what you are suggesting or not.

**Comment by xuchaoo** [comment]
@jeffbrown I use grails3 dynamic scaffolding, the code above is auto generateed. So I think it's a bug of scaffolding of grails3. We should 
```java
def login() {

        return [stock: new SomeBean()]
    }
```

**Comment by jeffbrown** [comment]
> I use grails3 dynamic scaffolding, the code above is auto generateed. So I think it's a bug of scaffolding of grails3.

Grails 3 doesn't support dynamic scaffolding and scaffolding is for domain objects.  I think the behavior in question is related to non-domain objects.  Am I mistaken about any of that?  It may be that I am misunderstanding.

Thanks again for your feedback.

**Comment by xuchaoo** [comment]
@jeffbrown grails3 use @Resource on domain class and command `genenrate-views` to support dynamic scaffolding. but I don't find this command ,so I use `generate-all` instead. but it show the  exception
```text
currently only supports domain types
```
then I add code in my controller
```java
def login() {

        return [stock: new SomeBean()]
    }
```

it works.

**Comment by jeffbrown** [comment]
> grails3 use @Resource on domain class and command genenrate-views to support dynamic scaffolding

I am sorry but I am not understanding a number of the comments above.  Please create a simple sample app which demonstrates a scenario that is relevant and push that to a public repo here on github.com and post a link here once that is ready.  That will probably clear this all up.

Thanks for the feedback.

**Comment by jeffbrown** [comment]
@xuchaoo  It looks like the comment has since been deleted but at one point above you had said the following:

> grails has so many bugs that I have to give up . It's heavy and not simple. gradle is also confused me.
People will not use grails to create a website which have big press. people just want to find a more quick method to implements CURD.

The CRUD stuff in Grails 3 is very simple to use.  I don't think it is heavy and complicated at all.  I am also not sure why Gradle is confusing you and how that relates to the problem here.  For an example see the project at https://github.com/jeffbrown/grails3crud.  In particular notice the commit at https://github.com/jeffbrown/grails3crud/commit/d6ddc4243c7e830022cdb7781f0cb045deaf7532.  All that I did there was write a simple `demo.Person` domain class and generate the default scaffolding.  I didn't have to make any changes to the generated scaffolding in order to make it work.  Can you run that app with `./gradlew run` and let me know if that works for you?  I am wondering if there might be something wrong in your dev environment that is complicating things.

Thanks again for your feedback.

**Comment by xuchaoo** [comment]
@jeffbrown Thank you jeff, your demo works well.

**Comment by xuchaoo** [comment]
@jeffbrown  I encounter a problem.  I run `grails run` or `gradle run` in my console and then I modify my grails code. But the console throws many exceptions and the app stoped, I have to restart my app. This costs so much time. How to solve this trouble?
![image](https://cloud.githubusercontent.com/assets/976008/7900751/fad2dd08-079a-11e5-8513-2502d12dc1be.png)
 Now I wondering if django has this problem.

**Comment by xuchaoo** [comment]
```
C:\code\play\smonitor>grails run-app
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:findMainClass
:bootRun
Grails application running at http://localhost:8080
ERROR grails.boot.GrailsApp - Application startup failed
java.lang.IllegalStateException: Failed to introspect annotations: public static java.util.List mystock.Stock.findAll(my
stock.Stock,java.util.Map)
        at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166) ~[spring-co
re-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73) ~[spring
-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
Exception in thread "Thread-10"         at org.springframework.core.type.StandardAnnotationMetadata.hasAnnotatedMethods(
StandardAnnotationMetadata.java:131) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassUtils.isLiteConfigurationCandidate(ConfigurationClas
sUtils.java:157) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
java.lang.IllegalStateException: Failed to introspect annotations: public static java.util.List mystock.Stock.findAll(my
stock.Stock,java.util.Map)
        at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:166)
        at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(Configuration
ClassUtils.java:108) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(Configura
tionClassPostProcessor.java:278) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:73)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(Conf
igurationClassPostProcessor.java:239) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.core.type.StandardAnnotationMetadata.hasAnnotatedMethods(StandardAnnotationMetadata.java:
131)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostPro
cessorRegistrationDelegate.java:119) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassUtils.isLiteConfigurationCandidate(ConfigurationClas
sUtils.java:157)
        at org.springframework.context.annotation.ConfigurationClassUtils.checkConfigurationClassCandidate(Configuration
ClassUtils.java:108)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplic
ationContext.java:606) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(Configura
tionClassPostProcessor.java:278)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:462) ~
[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(Conf
igurationClassPostProcessor.java:239)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostPro
cessorRegistrationDelegate.java:119)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplic
ationContext.java:606)
        at org.springframework.boot.context.embedded.Embe       at org.springframework.context.support.AbstractApplicati
onContext.refresh(AbstractApplicationContext.java:462)
ApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext
.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.3.RELEASE.ja
r:1.2.3.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.3.RELEASE.jar:1.
2.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at grails.boot.GrailsApp.super$2$run(GrailsApp.groovy) [grails-core-3.0.1.jar:3.0.1]
        at grails.boot.GrailsApp.super$2$run(GrailsApp.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
        at java.lang.   at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1
270) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
.Method.invoke(Method.java:606)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar:2.4.3]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130) [groov
y-2.4.3.jar:2.4.3]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:180) [grails-core-3.0.1.ja
r:3.0.1]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:130)
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy) [grails-core-3.0.1.jar:3.
0.1]
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy:180)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_67]
        at grails.boot.GrailsApp$_enableDevelopmentModeWatch_closure1.doCall(GrailsApp.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_67]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_67]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodIn at java.lang.reflect.Method.invoke(Method.java:6
06)
flectiveInterceptor.java:1270) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292) [groovy-2.4.3.
jar:2.4.3]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at groovy.lang.Closure.call(Closure.java:423) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.Closure.call(Closure.java:423)
        at groovy.lang.Closure.call(Closure.java:417) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.Closure.call(Closure.java:417)
        at groovy.lang.Closure.run(Closure.java:504) [groovy-2.4.3.jar:2.4.3]
        at groovy.lang.Closure.run(Closure.java:504)
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_67]
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
Caused by: java.lang.NullPointerException
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodGetDeclaredAnnotations(ReflectiveInterceptor.java:9
46) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodGetDeclaredAnnotations(ReflectiveInterceptor.java:9
46)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodGetAnnotations(ReflectiveInterceptor.java:1502)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodGetAnnotations(ReflectiveInterceptor.java:1502) [sp
ringloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrAccessibleObjectGetAnnotations(ReflectiveInterceptor.java
:1407)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrAccessibleObjectGetAnnotations(ReflectiveInterceptor.java
:1407) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrAnnotatedElementGetAnnotations(ReflectiveInterceptor.java
:1331)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrAnnotatedElementGetAnnotations(ReflectiveInterceptor.java
:1331) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192) ~[spring-
core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
org.springframework.core.annotation.AnnotatedElementUtils.doProcess(AnnotatedElementUtils.java:192)
        at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162)
        at org.springframework.core.annotation.AnnotatedElementUtils.process(AnnotatedElementUtils.java:162) ~[spring-co
re-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        ... 37 more
        ... 37 common frames omitted

BUILD SUCCESSFUL

Total time: 1 mins 24.193 secs
C:\code\play\smonitor>
```

I change my domain class code from 
```groovy
package mystock

import grails.rest.Resource

@Resource
class Stock {

    static hasMany = [tag: Tag]
    static hasOne = [notice: Notice]
    
    static constraints = {
        notice(nullable: true, display: false)
        tag(nullable: true, display: false)

        stockCode();
        stockName()
        givePrice();
        aimPrice();
        currentPrice();
        holdDays();
        isLong();
        giveDate();
        comments(nullable: true);
    }

    Notice notice;
    String stockName;
    String stockCode;

    double givePrice;//票价格
    double aimPrice;//预期目标价格
    double currentPrice;//当前价格
    double changePercentage;//变化（涨、跌）幅度
    int holdDays;//持票天数
    
    boolean isLong;//是否长线
    Date giveDate;//票日期
    
    String comments;//备注

}
```
TO
```groovy
package mystock

import grails.rest.Resource

@Resource
class Stock {

    static hasMany = [tag: Tag]
    static hasOne = [notice: Notice]
    
    static constraints = {
        notice(nullable: true)
        tag(nullable: true, display: false)

        stockCode();
        stockName()
        givePrice();
        aimPrice();
        currentPrice();
        holdDays();
        isLong();
        giveDate();
        comments(nullable: true);
    }

    Notice notice;
    String stockName;
    String stockCode;

    double givePrice;//票价格
    double aimPrice;//预期目标价格
    double currentPrice;//当前价格
    double changePercentage;//变化（涨、跌）幅度
    int holdDays;//持票天数
    
    boolean isLong;//是否长线
    Date giveDate;//票日期
    
    String comments;//备注

}
```

**Comment by xuchaoo** [comment]
U  can test my code https://github.com/xuchaoo/smonitor

**Comment by jeffbrown** [comment]
> U can test my code https://github.com/xuchaoo/smonitor

Can you clarify whatever steps are required to trigger the problem?

**Comment by xuchaoo** [comment]
@jeffbrown 
- start the app use command `grails run-app`
- modify  domain class `Stock `
FROM
```groovy
notice(nullable: true, display: false)
```
TO
```groovy
notice(nullable: true)
```
then my app stoped, console throws many exceptions.
Thank you .

**Comment by jeffbrown** [comment]
You don't even have to send any requests to the app to produce the problem?

**Comment by xuchaoo** [comment]
@jeffbrown  yes, after I modify the code , the app stoped  immediately.

**Comment by jeffbrown** [comment]
I am surprised that the `<f:all ...` tag is being invoked before any requests are sent to your app.  

Your comment says to change `notice(nullable: true, display: false)` to `notice(nullable: true)` but `notice(nullable: true)` is already there.  See https://github.com/xuchaoo/smonitor/blob/73b40d8e42193f20d7d5034b23c25a0df10db05a/grails-app/domain/mystock/Stock.groovy#L12.

**Comment by xuchaoo** [comment]
@jeffbrown 
reverse is also produce the problem.
change code FROM
```groovy
notice(nullable: true)
```
TO
```groovy
notice(nullable: true, display: false)
```

**Comment by xuchaoo** [comment]
@jeffbrown can you produce this problem?

**Comment by jeffbrown** [comment]
> @jeffbrown can you produce this problem?

No.  This is what I am seeing: http://jeffathome.s3.amazonaws.com/smonitor.mp4

**Comment by xuchaoo** [comment]
hi , @jeffbrown , after you run `gradlew run`, you should open http://localhost:8080/stock/create,  not just open http://localhost:8080

**Comment by xuchaoo** [comment]
I have a demo . http://pan.baidu.com/s/1sj0sq4X

**Comment by jeffbrown** [comment]
> after you run gradlew run, you should open http://localhost:8080/stock/create

I may have misunderstood what you meant when I asked if you had to send a request to the app in order to reproduce the problem and you said "after I modify the code , the app stopped immediately".

**Comment by jeffbrown** [comment]
I have tried sending requests to http://localhost:8080/stock/create after modifying the file and everything appears to work as I expect.

I expect that whatever you are seeing is a reloading problem.  If you stop the app and restart it, does the problem go away?

**Comment by xuchaoo** [comment]
sorry about my stupid English. You can reproduce my problem with the following steps:
- `gradlew run`
- open http://localhost:8080/stock/create
- modify code as I have said
- you can see many exceptions in the console, and  the app stoped

**Comment by xuchaoo** [comment]
@jeffbrown hi , please help me.

**Comment by jeffbrown** [comment]
@xuchaoo Can you create a simple sample app which demonstrates the problem and share that app in a public repo here at GitHub?  There are several things in the discussion here that don't make sense to me and having real runnable code will help clear that up.

**Comment by xuchaoo** [comment]
@jeffbrown  I make a video ,you can see. the code you can find at https://github.com/xuchaoo/smonitor

my video has been send to your email

**Comment by jeffbrown** [comment]
@xuchaoo I got the email that you sent to my personal account.  I am sorry that you are unhappy with the framework and I am doing everything that I can to help you but none of this is making sense to me.  I can't see anything in your video that has anything to do with the fields plugin and I can't reproduce the problem you are experiencing.

**Comment by xuchaoo** [comment]
@jeffbrown  you can reproduce my problem with the following step: DON'T forget to open localhost/stock/create after you run `gradlew run `/`gradle run`/`grails runApp`
- gradlew run
- open http://localhost:8080/stock/create
- modify code as I have said
- you can see many exceptions in the console, and the app stoped

may be this is not a bug of fileds plugins, but i'd like you can help me. Thank you .

**Comment by xuchaoo** [comment]
我做出了一个艰难决定，还是去学比较成熟的django吧。grails的bug特别多，我没有耐心总是跳这些坑。谢谢 @jeffbrown 的热心帮助。不过这个框架的某些方面还是十分前卫的，希望早日成熟。

**Comment by jeffbrown** [comment]
I am not sure why this issue was closed and https://github.com/grails/grails-core/issues/9030 was opened but I will leave this one closed and carry on the exchange over in the other issue.  I have just left a comment there along with a video demonstrating what this looks like at my end.  If you could review that and provide any feedback we would really appreciate it.

Thanks again.
