### ISSUE TITLE
Grails 3.0.1 Error executing tag <f:all>

### ISSUE THREAD

**Issue by jeffbrown** [grails3-plugins/fields#5]
*The text below has been copied and pasted directly from https://github.com/grails/grails-core/issues/711*

In Grails 3.0.1, I have a domain class like this:

    import java.time.LocalDate
    class Person {
         LocalDate birthDate
    }

When I do a generate-all, run the app, and try to create a new instance of the person, the following error occurs:

````
ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.grails.gsp.GroovyPagesException: Error processing GroovyPageView: [views/conference/create.gsp:35] Error executing tag <g:form>: [views/conference/create.gsp:30] Error executing tag <f:all>: null] with root cause
java.lang.NullPointerException: null
	at grails.plugin.formfields.FormFieldsTagLib$_renderDefaultField_closure13.doCall(FormFieldsTagLib.groovy:370) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib.renderDefaultField(FormFieldsTagLib.groovy:363) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure3.doCall(FormFieldsTagLib.groovy:133) ~[fields-2.0.1.jar:na]
	at grails.plugin.formfields.FormFieldsTagLib$_closure2.doCall(FormFieldsTagLib.groovy:79) ~[fields-2.0.1.jar:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp$_run_closure2$_closure24.doCall(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:73) ~[na:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp$_run_closure2.doCall(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:78) ~[na:na]
	at Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp.run(Users_erikp_Userfiles_projects_conference_grails_admin_grails_app_views_conference_create_gsp:81) ~[na:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
````

**Comment by graemerocher** [comment]
fixed by https://github.com/grails3-plugins/fields/commit/e042dee24253b3029075e664dba2127b0e590d58
